# check_06_observability.py (acceptance-tests/checks)
#
# Closes the loop on the specific customer-demo requirement this suite
# was built for: "a customer looks into the NAT server -- we should have
# everything in our observability." This check doesn't drive any traffic
# itself (checks 02/05 already do that) -- it verifies the OBSERVABILITY
# STACK ITSELF is actually up and actually has data, so a demo doesn't
# discover a blank Grafana panel live in front of a customer.
#
# -----------------------------------------------------
# What this verifies:
#
# 1) Prometheus (`control_plane.prometheus_url`) is reachable and its
#    `up{job="nat_exporter"}` target set is not empty -- i.e. Prometheus
#    is actually scraping real nodes, not just running with an empty
#    config.
# 2) Grafana (`control_plane.grafana_url`) answers `/api/health`.
# 3) Alertmanager (`control_plane.alertmanager_url`) answers
#    `/api/v2/status`, if configured (optional -- some deployments run
#    Alertmanager with no external endpoint exposed at all).
# 4) Per pool: `nat_node_healthy` has data -- docs/OBSERVABILITY.md and
#    this suite's own commit history singled out NAT visibility as
#    needing full parity in the observability stack.
#
# -----------------------------------------------------
# Usage:
#
# python run_acceptance_tests.py --only 06-observability
#
# -----------------------------------------------------
# Best Practices:
#
# - Run this LAST (it already is, alphabetically) -- if checks 01-05 have
#   been run first, this check's Prometheus queries are validating real,
#   fresh data generated by this very suite, which is exactly the kind of
#   walkthrough worth recording for a customer demo (see the demo runbook
#   this suite ships alongside, docs/DEMO.md).
#
# -----------------------------------------------------
# Author:
# - Sandip Gangdhar
# - GitHub: https://github.com/sandipgangdhar
#
# (c) Linode-NAT-Gateway (LNG) | Developed by Sandip Gangdhar | 2026
# -----------------------------------------------------
"""
Observability-stack reachability + metric-presence check:
Prometheus/Grafana/Alertmanager are up, and NAT has real data in
Prometheus for every configured pool.
"""
from __future__ import annotations

import time

import requests

from lib.http_client import request_with_backoff
from lib.reporter import Reporter
from lib.config import Config

CHECK_ID = "06-observability"
DESCRIPTION = "Prometheus/Grafana/Alertmanager are reachable, with real NAT data"


def _query_has_results(prometheus_url: str, query: str) -> bool:
    resp = request_with_backoff("GET", f"{prometheus_url}/api/v1/query", params={"query": query}, timeout=10)
    resp.raise_for_status()
    return bool(resp.json()["data"]["result"])


def run(cfg: Config, report: Reporter) -> None:
    started = time.monotonic()
    prometheus_url = cfg.control_plane.get("prometheus_url")
    grafana_url = cfg.control_plane.get("grafana_url")
    alertmanager_url = cfg.control_plane.get("alertmanager_url")

    if not prometheus_url:
        report.skipped(CHECK_ID, "control_plane.prometheus_url not set in config.yaml", started)
        return

    try:
        targets_up = _query_has_results(prometheus_url, 'up{job="nat_exporter"} == 1')
    except (requests.exceptions.RequestException, ValueError, KeyError) as exc:
        report.failed(CHECK_ID, f"Prometheus unreachable or query failed at {prometheus_url}: {exc}", started)
        return

    if not targets_up:
        report.failed(CHECK_ID, f"Prometheus at {prometheus_url} has zero up nat_exporter targets -- fleet-aware scraping (file_sd) may be misconfigured", started)
        return

    problems: list[str] = []

    if grafana_url:
        try:
            g = request_with_backoff("GET", f"{grafana_url}/api/health", timeout=10)
            if g.status_code != 200:
                problems.append(f"Grafana /api/health at {grafana_url} returned HTTP {g.status_code}")
        except requests.exceptions.RequestException as exc:
            problems.append(f"Grafana unreachable at {grafana_url}: {exc}")

    if alertmanager_url:
        try:
            a = request_with_backoff("GET", f"{alertmanager_url}/api/v2/status", timeout=10)
            if a.status_code != 200:
                problems.append(f"Alertmanager /api/v2/status at {alertmanager_url} returned HTTP {a.status_code}")
        except requests.exceptions.RequestException as exc:
            problems.append(f"Alertmanager unreachable at {alertmanager_url}: {exc}")

    for pool_name, pool in cfg.pools.items():
        try:
            if not _query_has_results(prometheus_url, f'nat_node_healthy{{pool="{pool_name}"}}'):
                problems.append(f"{pool_name}: no nat_node_healthy series in Prometheus (NAT has no visibility)")
        except (requests.exceptions.RequestException, ValueError, KeyError) as exc:
            problems.append(f"{pool_name}: nat_node_healthy query failed: {exc}")

    if problems:
        report.failed(CHECK_ID, "; ".join(problems), started)
        return

    report.passed(CHECK_ID, f"Prometheus/Grafana/Alertmanager reachable; NAT data is live in Prometheus across {len(cfg.pools)} pool(s)", started)
